### PR TITLE
Added readme.md file.

### PR DESCRIPTION
**Pull request by Rohan-cod**

### CODE REVIEW

**Comment by zhuyifei1999** [comment]
Is there a reason to change from non-markdown to markdown?

**Comment by Rohan-cod** [comment]
Markdown markup language makes the documentation look aesthetically pleasing. It has also been adopted by the technical writing community as a solution for writing documentation.

**Comment by zhuyifei1999** [comment]
> Markdown markup language makes the documentation look aesthetically pleasing. It has also been adopted by the technical writing community as a solution for writing documentation.

I think it would be a good idea to document that in the commit message.

However, non-markdown [may have been intentional](https://github.com/toolforge/tool-toolforge-static/commits/master).

**Comment by Rohan-cod** [comment]
Yes, this was done to make the readme readable [here](https://tools-static.wmflabs.org/toolforge/). 
But we can have both, a txt and md file in the same repository. By doing this both purpose will be fulfilled.

**Comment by Rohan-cod** [comment]
Hi @zhuyifei1999, I have added README.txt file back. Now there are both Markdown and non-Markdown versions of the readme.

**Comment by zhuyifei1999** [comment]
I personally dislike duplication, but I don't maintain this tool, so @bd808 gets the say in whether to merge or not. 

I would also suggest squashing the changes to a single commit with the commit message explaining the rationale.

**Comment by Rohan-cod** [comment]
Should I close this Pr and send another pr?

**Comment by zhuyifei1999** [comment]
You don't have to. See posts like https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by Rohan-cod** [comment]
@zhuyifei1999, I have squashed the commits into one commit.

**Comment by zhuyifei1999** [comment]
> with the commit message explaining the rationale [of this PR]

The point of squashing the commits is that the commit logs don't get flooded with not-ready states, just like gerrit where you usually submit a patch set in a single commit after revisions by amending it.

The point of explaining the rationale is to find out why exactly a commit happened in the first place as simple as possible. If the commit only says "Merged #1", not everyone knows immediately that the number is a GitHub PR.
Repos can move, GitHub, GitLab, Gerrit, Diffusion. While PRs aren't typically deleted if they happen, it would be lots of extra work under those circumstances to "dig history" to figure out what was going on, so always summarize what you did and why you did the commit in the commit message.

See https://www.mediawiki.org/wiki/Gerrit/Commit_message_guidelines

In any case

> I don't maintain this tool, so @bd808 gets the say in whether to merge or not.

**Comment by Rohan-cod** [comment]
@zhuyifei1999, can you please ask @bd808 to review it.

**Comment by bd808** [comment]
@Rohan-cod The existing file is actually in Markdown format. All that is needed to make this prettier on GitHub is moving the exiting file from README.txt to README.md. That would functionally be reverting 3980848632081985203b8f7543f80c2bb98a2cd0 which was done so that the file could be read in-browser at https://tools-static.wmflabs.org/toolforge/README.txt.

I honestly don't think that making the repo look prettier on GitHub at the expense of the files being readable on the live deployment is a good idea.

**Comment by Rohan-cod** [comment]
@bd808, On GitHub the users will see the README.md file in the readme section and [here](https://tools-static.wmflabs.org/toolforge/README.txt ) users can view the README.txt file. On both the platforms users will get a pretty documentation.

**Comment by bd808** [comment]
> @bd808, On GitHub the users will see the README.md file in the readme section and [here](https://tools-static.wmflabs.org/toolforge/README.txt) users can view the README.txt file. On both the platforms users will get a pretty documentation.

Duplicating this documentation for GitHub viewing is not useful in my opinion. These docs will get out of sync with each other. How about we make README.md a symlink to the existing README.txt and call it good?

**Comment by Rohan-cod** [comment]
You mean adding a link to the README.md file in the README.txt file?

**Comment by bd808** [comment]
> You mean adding a link to the README.md file in the README.txt file?

No. I mean creating a git commit which includes a symlink created via `ln -s README.txt README.md` so that in a clone of the repository there are 2 files (README.txt and README.md) which are actually the same physical file at the file system level.

**Comment by Rohan-cod** [comment]
Okay, thanks for the help @bd808, I will do the changes and commit them.

**Comment by Rohan-cod** [comment]
@bd808, I have made README.md a symlink to README.txt.

**Comment by bd808** [comment]
Merged as b550c065c22136d1881cc3d66983acc9137f217d

**Comment by Rohan-cod** [comment]
Thank you @bd808 :)

**Pull request closed without merging**
